defaults:
  - _self_
  - hydra: default
  - model: flow4D
  
slurm_id: 00000

wandb_mode: online # [offline, disabled, online]
wandb_project_name: MambaFlow

# Datasets: # choices: [Argoverse2, Waymo]
dataset: Argoverse2

# Argoverse 2
dataset_path: /data/jiehao/dataset/deflow/demo_data/av2/preprocess_v2/sensor
#dataset_path: /data/jiehao/dataset/deflow/av2/preprocess/sensor

# Waymo
#dataset_path: /data/jiehao/dataset/deflow/waymo/flowlabel/preprocess

checkpoint:
pretrained_weights:
output: ${model.name}-${slurm_id}
eval_only: False

# trainer
num_workers: 16
gpus: 1 # will change in code: torch.cuda.device_count()
sync_bn: true
batch_size: 5
epochs: 20
gradient_clip_val: 5.0
gradient_clip_algorithm: "norm"
debug: False

version: 2024

lr: 2e-4
loss_fn: mambaflowLoss # choices: [ff3dLoss, zeroflowLoss, deflowLoss, weigthedflowLoss, mambaflowLoss]
semantic_loss: False

# log settings
seed: 42069
log_every: 10 # steps epochs*dataset_size/batch_size
val_every: 1 # epochs
save_top_model: 10 # top_k model will be saved.

# -----> Model and Task Parameters
voxel_size: [0.2, 0.2, 0.2]
point_cloud_range: [-51.2, -51.2, -2.2, 51.2, 51.2, 4.2]
variation: 1
num_frames: 5

