name: fastflow3d

target:
  _target_: scripts.network.models.fastflow3d.FastFlow3D
  bottleneck_head: False
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}

val_monitor: val/Three-way