name: Close inactive issues
on:
  schedule:
    - cron: "35 11 * * *"

env:
  DAYS_BEFORE_ISSUE_STALE: 14
  DAYS_BEFORE_ISSUE_CLOSE: 14

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: ${{ env.DAYS_BEFORE_ISSUE_STALE }}
          days-before-issue-close: ${{ env.DAYS_BEFORE_ISSUE_CLOSE }}
          stale-issue-label: "stale"
          stale-issue-message: |
            This issue is stale because it has been open for ${{ env.DAYS_BEFORE_ISSUE_STALE }} days with no activity. 
            Please consider close it if the discussion already solve your question. Or it will be closed automatically if no further activity occurs. 
          close-issue-message: |
            This issue is being closed because it has been stale for ${{ env.DAYS_BEFORE_ISSUE_CLOSE }} days with no activity.
            You can still comment if you have further questions or information to add.
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}